export const COMMANDS = {
  // Query
  EXECUTE_QUERY: "execute_query",
  CANCEL_QUERY: "cancel_query",
  EXECUTE_BY_CONN: "execute_by_conn",
  LIST_SQL_EXECUTION_LOGS: "list_sql_execution_logs",
  LIST_REDIS_COMMAND_LOGS: "list_redis_command_logs",

  // Connections
  GET_CONNECTIONS: "get_connections",
  CREATE_CONNECTION: "create_connection",
  UPDATE_CONNECTION: "update_connection",
  DELETE_CONNECTION: "delete_connection",
  CREATE_DATABASE_BY_ID: "create_database_by_id",
  GET_MYSQL_CHARSETS_BY_ID: "get_mysql_charsets_by_id",
  GET_MYSQL_COLLATIONS_BY_ID: "get_mysql_collations_by_id",
  TEST_CONNECTION_EPHEMERAL: "test_connection_ephemeral",
  TEST_CONNECTION_SAVED_EDIT: "test_connection_saved_edit",
  LIST_SQLITE_ISSUES: "list_sqlite_issues",
  IMPORT_CONNECTIONS: "import_connections",

  // Saved Queries
  GET_SAVED_QUERIES: "get_saved_queries",
  SAVE_QUERY: "save_query",
  UPDATE_SAVED_QUERY: "update_saved_query",
  DELETE_SAVED_QUERY: "delete_saved_query",

  // Metadata
  LIST_TABLES: "list_tables",
  LIST_ROUTINES: "list_routines",
  GET_TABLE_STRUCTURE: "get_table_structure",
  GET_TABLE_DDL: "get_table_ddl",
  GET_ROUTINE_DDL: "get_routine_ddl",
  GET_TABLE_METADATA: "get_table_metadata",
  LIST_TABLES_BY_CONN: "list_tables_by_conn",
  LIST_DATABASES: "list_databases",
  LIST_DATABASES_BY_ID: "list_databases_by_id",
  LIST_SCHEMAS: "list_schemas",
  GET_SCHEMA_OVERVIEW: "get_schema_overview",
  GET_SCHEMA_FOREIGN_KEYS: "get_schema_foreign_keys",
  LIST_EVENTS: "list_events",
  LIST_SEQUENCES: "list_sequences",
  LIST_TYPES: "list_types",
  LIST_SYNONYMS: "list_synonyms",
  LIST_PACKAGES: "list_packages",
  GET_DRIVER_CAPABILITIES: "get_driver_capabilities",

  // Table Data
  GET_TABLE_DATA: "get_table_data",
  GET_TABLE_DATA_BY_CONN: "get_table_data_by_conn",

  // Export / Import
  EXPORT_TABLE_DATA: "export_table_data",
  EXPORT_DATABASE_SQL: "export_database_sql",
  EXPORT_QUERY_RESULT: "export_query_result",
  IMPORT_SQL_FILE: "import_sql_file",

  // Redis
  REDIS_LIST_DATABASES: "redis_list_databases",
  REDIS_SCAN_KEYS: "redis_scan_keys",
  REDIS_GET_KEY: "redis_get_key",
  REDIS_SET_KEY: "redis_set_key",
  REDIS_UPDATE_KEY: "redis_update_key",
  REDIS_DELETE_KEY: "redis_delete_key",
  REDIS_RENAME_KEY: "redis_rename_key",
  REDIS_SET_TTL: "redis_set_ttl",
  REDIS_GET_KEY_PAGE: "redis_get_key_page",
  REDIS_GET_STREAM_RANGE: "redis_get_stream_range",
  REDIS_GET_STREAM_VIEW: "redis_get_stream_view",
  REDIS_XGROUP_CREATE: "redis_xgroup_create",
  REDIS_XGROUP_DEL: "redis_xgroup_del",
  REDIS_XGROUP_SETID: "redis_xgroup_setid",
  REDIS_XACK: "redis_xack",
  REDIS_XPENDING: "redis_xpending",
  REDIS_XCLAIM: "redis_xclaim",
  REDIS_XTRIM: "redis_xtrim",
  REDIS_XREADGROUP: "redis_xreadgroup",
  REDIS_EXECUTE_RAW: "redis_execute_raw",
  REDIS_PATCH_KEY: "redis_patch_key",
  REDIS_BITMAP_GET_BIT: "redis_bitmap_get_bit",
  REDIS_BITMAP_COUNT: "redis_bitmap_count",
  REDIS_BITMAP_POS: "redis_bitmap_pos",
  REDIS_HLL_PFADD: "redis_hll_pfadd",
  REDIS_GEO_ADD: "redis_geo_add",
  REDIS_GEO_POS: "redis_geo_pos",
  REDIS_GEO_DIST: "redis_geo_dist",
  REDIS_GEO_SEARCH: "redis_geo_search",
  REDIS_SERVER_INFO: "redis_server_info",
  REDIS_SERVER_CONFIG: "redis_server_config",
  REDIS_SLOWLOG_GET: "redis_slowlog_get",
  REDIS_ZRANGEBYSCORE: "redis_zrangebyscore",
  REDIS_ZRANK: "redis_zrank",
  REDIS_SET_OPERATION: "redis_set_operation",
  REDIS_SISMEMBER: "redis_sismember",
  REDIS_SMOVE: "redis_smove",
  REDIS_BATCH_KEY_OPS: "redis_batch_key_ops",
  REDIS_MGET: "redis_mget",
  REDIS_MSET: "redis_mset",
  REDIS_CLUSTER_INFO: "redis_cluster_info",
  REDIS_ZSCORE: "redis_zscore",
  REDIS_ZMSCORE: "redis_zmscore",
  REDIS_ZRANGEBYLEX: "redis_zrangebylex",
  REDIS_ZLEXCOUNT: "redis_zlexcount",
  REDIS_ZPOPMIN: "redis_zpopmin",
  REDIS_ZPOPMAX: "redis_zpopmax",
  REDIS_LINDEX: "redis_lindex",
  REDIS_LPOS: "redis_lpos",
  REDIS_LTRIM: "redis_ltrim",
  REDIS_LINSERT: "redis_linsert",
  REDIS_LMOVE: "redis_lmove",

  // Elasticsearch
  ELASTICSEARCH_TEST_CONNECTION: "elasticsearch_test_connection",
  ELASTICSEARCH_TEST_CONNECTION_EPHEMERAL: "elasticsearch_test_connection_ephemeral",
  ELASTICSEARCH_LIST_INDICES: "elasticsearch_list_indices",
  ELASTICSEARCH_GET_INDEX_MAPPING: "elasticsearch_get_index_mapping",
  ELASTICSEARCH_CREATE_INDEX: "elasticsearch_create_index",
  ELASTICSEARCH_DELETE_INDEX: "elasticsearch_delete_index",
  ELASTICSEARCH_REFRESH_INDEX: "elasticsearch_refresh_index",
  ELASTICSEARCH_OPEN_INDEX: "elasticsearch_open_index",
  ELASTICSEARCH_CLOSE_INDEX: "elasticsearch_close_index",
  ELASTICSEARCH_SEARCH_DOCUMENTS: "elasticsearch_search_documents",
  ELASTICSEARCH_GET_DOCUMENT: "elasticsearch_get_document",
  ELASTICSEARCH_UPSERT_DOCUMENT: "elasticsearch_upsert_document",
  ELASTICSEARCH_DELETE_DOCUMENT: "elasticsearch_delete_document",
  ELASTICSEARCH_EXPORT_DOCUMENTS: "elasticsearch_export_documents",
  ELASTICSEARCH_IMPORT_DOCUMENTS: "elasticsearch_import_documents",
  ELASTICSEARCH_EXECUTE_RAW: "elasticsearch_execute_raw",

  // MongoDB
  MONGODB_TEST_CONNECTION: "mongodb_test_connection",
  MONGODB_TEST_CONNECTION_EPHEMERAL: "mongodb_test_connection_ephemeral",
  MONGODB_LIST_DATABASES: "mongodb_list_databases",
  MONGODB_LIST_COLLECTIONS: "mongodb_list_collections",
  MONGODB_FIND_DOCUMENTS: "mongodb_find_documents",
  MONGODB_INSERT_DOCUMENT: "mongodb_insert_document",
  MONGODB_DELETE_DOCUMENT: "mongodb_delete_document",
  MONGODB_UPDATE_DOCUMENT: "mongodb_update_document",
  MONGODB_GET_DOCUMENT: "mongodb_get_document",

  // AI
  AI_LIST_PROVIDERS: "ai_list_providers",
  AI_CREATE_PROVIDER: "ai_create_provider",
  AI_UPDATE_PROVIDER: "ai_update_provider",
  AI_DELETE_PROVIDER: "ai_delete_provider",
  AI_SET_DEFAULT_PROVIDER: "ai_set_default_provider",
  AI_CLEAR_PROVIDER_API_KEY: "ai_clear_provider_api_key",
  AI_CHAT_START: "ai_chat_start",
  AI_CHAT_CONTINUE: "ai_chat_continue",
  AI_LIST_CONVERSATIONS: "ai_list_conversations",
  AI_GET_CONVERSATION: "ai_get_conversation",
  AI_DELETE_CONVERSATION: "ai_delete_conversation",

  // MCP
  MCP_STATUS: "mcp_status",
  MCP_START: "mcp_start",
  MCP_STOP: "mcp_stop",
  MCP_GET_TOOLS: "mcp_get_tools",
  MCP_DETECT_CLIENTS: "mcp_detect_clients",
  MCP_CONFIGURE_CLIENT: "mcp_configure_client",

  // System
  LIST_SYSTEM_FONTS: "list_system_fonts",
} as const;

export type CommandName = (typeof COMMANDS)[keyof typeof COMMANDS];
export type { CommandMap, CommandArgs, CommandReturn } from "./commands/types";
