use crate::error::AppError;
use crate::models::{
    ColumnInfo, ColumnSchema, ForeignKeyInfo, IndexInfo, RoutineInfo, SchemaForeignKey,
    SchemaOverview, SequenceInfo, TableInfo, TableMetadata, TableSchema, TableStructure, TypeInfo,
};
use sqlx::Row;
use std::collections::{HashMap, HashSet};

fn query_error(message: impl Into<String>) -> AppError {
    AppError::query_failed(message)
}

pub struct PgColumnInfo {
    pub name: String,
    pub data_type: String,
    pub is_nullable: bool,
    pub default_value: Option<String>,
    pub identity: Option<String>,
}

pub struct PgKeyConstraint {
    pub name: String,
    pub constraint_type: String,
    pub columns: Vec<String>,
}

#[allow(dead_code)]
pub struct PgIndexInfo {
    pub name: String,
    pub unique: bool,
    pub index_type: String,
    pub columns: Vec<String>,
    pub condition: Option<String>,
    pub full_statement: String,
}

pub fn pg_quote_ident(ident: &str) -> String {
    if ident.is_empty() {
        return "\"\"".to_string();
    }
    format!("\"{}\"", ident.replace('"', "\"\""))
}

pub fn pg_qualified_table(schema: &str, table: &str) -> String {
    format!("{}.{}", pg_quote_ident(schema), pg_quote_ident(table))
}

fn pg_quote_literal(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

pub fn is_high_precision_pg_type(data_type: &str, udt_name: &str) -> bool {
    let data_type = data_type.to_ascii_lowercase();
    let udt_name = udt_name.to_ascii_lowercase();
    matches!(
        data_type.as_str(),
        "bigint" | "numeric" | "decimal" | "money"
    ) || matches!(udt_name.as_str(), "int8" | "numeric" | "decimal" | "money")
}

pub fn decode_postgres_text_cell(
    row: &sqlx::postgres::PgRow,
    idx: usize,
) -> Result<String, AppError> {
    if let Ok(v) = row.try_get::<String, _>(idx) {
        return Ok(v);
    }
    if let Ok(v) = row.try_get::<Vec<u8>, _>(idx) {
        return Ok(String::from_utf8_lossy(&v).to_string());
    }
    Err(query_error(format!(
        "Failed to decode Postgres text column at index {idx}"
    )))
}

pub fn decode_postgres_optional_text_cell(
    row: &sqlx::postgres::PgRow,
    idx: usize,
) -> Result<Option<String>, AppError> {
    if let Ok(v) = row.try_get::<Option<String>, _>(idx) {
        return Ok(v);
    }
    if let Ok(v) = row.try_get::<Option<Vec<u8>>, _>(idx) {
        return Ok(v.map(|b| String::from_utf8_lossy(&b).to_string()));
    }
    if let Ok(v) = row.try_get::<String, _>(idx) {
        return Ok(Some(v));
    }
    if let Ok(v) = row.try_get::<Vec<u8>, _>(idx) {
        return Ok(Some(String::from_utf8_lossy(&v).to_string()));
    }
    Err(query_error(format!(
        "Failed to decode Postgres optional text column at index {idx}"
    )))
}

fn extract_pg_index_columns(full_def: &str) -> Option<Vec<String>> {
    let upper = full_def.to_uppercase();
    let table_end = upper
        .find(")\n")
        .or_else(|| upper.find(") WHERE"))
        .or_else(|| upper.find(") INCLUDE"))
        .unwrap_or(full_def.len());
    let prefix = &full_def[..table_end];
    let open = prefix.rfind('(')?;
    let content = &full_def[open + 1..];
    let close = content.find(')')?;
    let col_list = &content[..close];
    if col_list.trim().is_empty() {
        return None;
    }
    let cols: Vec<String> = col_list
        .split(',')
        .map(|c| c.trim().trim_matches('"').to_string())
        .filter(|c| !c.is_empty())
        .collect();
    if cols.is_empty() {
        None
    } else {
        Some(cols)
    }
}

fn render_pg_create_table_ddl(
    schema: &str,
    table: &str,
    columns: &[PgColumnInfo],
    key_constraints: &[PgKeyConstraint],
    check_constraints: &[(String, String)],
    foreign_keys: &[ForeignKeyInfo],
    indexes: &[PgIndexInfo],
    table_comment: Option<&str>,
    column_comments: &HashMap<String, String>,
) -> String {
    let mut lines: Vec<String> = Vec::new();

    for col in columns {
        let mut line = format!("    {} {}", pg_quote_ident(&col.name), col.data_type);
        if let Some(ref identity) = col.identity {
            match identity.as_str() {
                "a" => line.push_str(" GENERATED ALWAYS AS IDENTITY"),
                "d" => line.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
                _ => {}
            }
        }
        if !col.is_nullable {
            line.push_str(" NOT NULL");
        }
        if let Some(ref default) = col.default_value {
            line.push_str(&format!(" DEFAULT {}", default));
        }
        lines.push(line);
    }

    for kc in key_constraints {
        let cols: Vec<String> = kc.columns.iter().map(|c| pg_quote_ident(c)).collect();
        lines.push(format!(
            "    CONSTRAINT {} {} ({})",
            pg_quote_ident(&kc.name),
            kc.constraint_type,
            cols.join(", ")
        ));
    }

    for (name, definition) in check_constraints {
        lines.push(format!(
            "    CONSTRAINT {} CHECK {}",
            pg_quote_ident(name),
            definition
        ));
    }

    for fk in foreign_keys {
        let ref_schema = fk.referenced_schema.as_deref().unwrap_or(schema);
        let mut fk_line = format!(
            "    CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {}.{} ({})",
            pg_quote_ident(&fk.name),
            pg_quote_ident(&fk.column),
            pg_quote_ident(ref_schema),
            pg_quote_ident(&fk.referenced_table),
            pg_quote_ident(&fk.referenced_column),
        );
        if let Some(ref action) = fk.on_update {
            if action != "NO ACTION" {
                fk_line.push_str(&format!(" ON UPDATE {}", action));
            }
        }
        if let Some(ref action) = fk.on_delete {
            if action != "NO ACTION" {
                fk_line.push_str(&format!(" ON DELETE {}", action));
            }
        }
        lines.push(fk_line);
    }

    let body = lines.join(",\n");
    let mut ddl = format!(
        "-- Note: This DDL is reconstructed from table metadata.\n\
         CREATE TABLE {}.{} (\n{}\n);",
        pg_quote_ident(schema),
        pg_quote_ident(table),
        body
    );

    for idx in indexes {
        ddl.push_str(&format!("\n{};", idx.full_statement));
    }

    if let Some(comment) = table_comment {
        ddl.push_str(&format!(
            "\nCOMMENT ON TABLE {}.{} IS {};",
            pg_quote_ident(schema),
            pg_quote_ident(table),
            pg_quote_literal(comment)
        ));
    }

    for (col_name, comment) in column_comments {
        ddl.push_str(&format!(
            "\nCOMMENT ON COLUMN {}.{}.{} IS {};",
            pg_quote_ident(schema),
            pg_quote_ident(table),
            pg_quote_ident(col_name),
            pg_quote_literal(comment)
        ));
    }

    ddl
}

pub struct PostgresMetadata {
    pub pool: sqlx::PgPool,
}

impl PostgresMetadata {
    pub async fn list_databases(&self) -> Result<Vec<String>, AppError> {
        let rows: Vec<(String,)> = sqlx::query_as(
            "SELECT datname FROM pg_database WHERE datistemplate = false ORDER BY datname",
        )
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;
        Ok(rows.into_iter().map(|r| r.0).collect())
    }

    pub async fn list_schemas(&self) -> Result<Vec<String>, AppError> {
        let rows: Vec<(String,)> = sqlx::query_as(
            "SELECT nspname FROM pg_namespace \
             WHERE nspname NOT LIKE 'pg_%' \
               AND nspname != 'information_schema' \
             ORDER BY nspname",
        )
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;
        Ok(rows.into_iter().map(|r| r.0).collect())
    }

    pub async fn list_tables(&self, schema: Option<String>) -> Result<Vec<TableInfo>, AppError> {
        let rows = if let Some(schema) = schema {
            sqlx::query(
                "SELECT table_schema, table_name, table_type \
                 FROM information_schema.tables \
                 WHERE table_schema = $1 AND table_type IN ('BASE TABLE','VIEW') \
                 ORDER BY table_name",
            )
            .bind(&schema)
            .fetch_all(&self.pool)
            .await
            .map_err(|e| query_error(e.to_string()))?
        } else {
            sqlx::query(
                "SELECT table_schema, table_name, table_type \
                 FROM information_schema.tables \
                 WHERE table_schema NOT IN ('information_schema', 'pg_catalog') \
                   AND table_schema NOT LIKE 'pg_toast%' \
                   AND table_type IN ('BASE TABLE','VIEW') \
                 ORDER BY table_schema, table_name",
            )
            .fetch_all(&self.pool)
            .await
            .map_err(|e| query_error(e.to_string()))?
        };

        let mut res = Vec::new();
        for row in rows {
            res.push(TableInfo {
                schema: decode_postgres_text_cell(&row, 0).unwrap_or_else(|_| "public".to_string()),
                name: decode_postgres_text_cell(&row, 1).unwrap_or_default(),
                r#type: decode_postgres_text_cell(&row, 2).unwrap_or_else(|_| "table".to_string()),
            });
        }
        Ok(res)
    }

    pub async fn get_table_structure(
        &self,
        schema: String,
        table: String,
    ) -> Result<TableStructure, AppError> {
        let pk_rows: Vec<(String,)> = sqlx::query_as(
            r#"
            SELECT a.attname
            FROM pg_index i
            JOIN pg_class c ON c.oid = i.indrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS k(attnum, ord) ON true
            JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k.attnum
            WHERE i.indisprimary = true
              AND n.nspname = $1
              AND c.relname = $2
            ORDER BY k.ord
            "#,
        )
        .bind(&schema)
        .bind(&table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let pk_set: HashSet<String> = pk_rows.into_iter().map(|r| r.0).collect();

        let rows = sqlx::query(
            r#"
            SELECT
              a.attname AS column_name,
              format_type(a.atttypid, a.atttypmod) AS column_type,
              a.attnotnull AS not_null,
              pg_get_expr(ad.adbin, ad.adrelid) AS column_default,
              d.description AS comment
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_attribute a ON a.attrelid = c.oid
            LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
            LEFT JOIN pg_description d ON d.objoid = a.attrelid AND d.objsubid = a.attnum
            WHERE n.nspname = $1
              AND c.relname = $2
              AND a.attnum > 0
              AND NOT a.attisdropped
            ORDER BY a.attnum
            "#,
        )
        .bind(&schema)
        .bind(&table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut columns = Vec::new();
        for row in rows {
            let name = decode_postgres_text_cell(&row, 0)?;
            let not_null: bool = row.try_get(2).unwrap_or(false);
            let comment = decode_postgres_optional_text_cell(&row, 4)?;
            let comment = comment.and_then(|c| {
                let trimmed = c.trim().to_string();
                if trimmed.is_empty() {
                    None
                } else {
                    Some(trimmed)
                }
            });

            columns.push(ColumnInfo {
                name: name.clone(),
                r#type: decode_postgres_text_cell(&row, 1)?,
                nullable: !not_null,
                default_value: decode_postgres_optional_text_cell(&row, 3)?,
                primary_key: pk_set.contains(&name),
                comment,
                default_constraint_name: None,
            });
        }
        Ok(TableStructure { columns })
    }

    pub async fn get_table_metadata(
        &self,
        schema: String,
        table: String,
    ) -> Result<TableMetadata, AppError> {
        let pk_rows: Vec<(String,)> = sqlx::query_as(
            r#"
            SELECT a.attname
            FROM pg_index i
            JOIN pg_class c ON c.oid = i.indrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS k(attnum, ord) ON true
            JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k.attnum
            WHERE i.indisprimary = true
              AND n.nspname = $1
              AND c.relname = $2
            ORDER BY k.ord
            "#,
        )
        .bind(&schema)
        .bind(&table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let pk_set: HashSet<String> = pk_rows.into_iter().map(|r| r.0).collect();

        let column_rows = sqlx::query(
            r#"
            SELECT
              a.attname AS column_name,
              format_type(a.atttypid, a.atttypmod) AS column_type,
              a.attnotnull AS not_null,
              pg_get_expr(ad.adbin, ad.adrelid) AS column_default,
              d.description AS comment
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_attribute a ON a.attrelid = c.oid
            LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
            LEFT JOIN pg_description d ON d.objoid = a.attrelid AND d.objsubid = a.attnum
            WHERE n.nspname = $1
              AND c.relname = $2
              AND a.attnum > 0
              AND NOT a.attisdropped
            ORDER BY a.attnum
            "#,
        )
        .bind(&schema)
        .bind(&table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut columns = Vec::new();
        for row in column_rows {
            let name = decode_postgres_text_cell(&row, 0)?;
            let comment = decode_postgres_optional_text_cell(&row, 4)?;
            let comment = comment.and_then(|c| {
                let trimmed = c.trim().to_string();
                if trimmed.is_empty() {
                    None
                } else {
                    Some(trimmed)
                }
            });
            let not_null: bool = row.try_get(2).unwrap_or(false);

            columns.push(ColumnInfo {
                name: name.clone(),
                r#type: decode_postgres_text_cell(&row, 1)?,
                nullable: !not_null,
                default_value: decode_postgres_optional_text_cell(&row, 3)?,
                primary_key: pk_set.contains(&name),
                comment,
                default_constraint_name: None,
            });
        }

        let index_rows = sqlx::query(
            r#"
            SELECT
              ic.relname AS index_name,
              i.indisunique AS is_unique,
              am.amname AS index_type,
              array_agg(a.attname ORDER BY k.ord) FILTER (WHERE a.attname IS NOT NULL) AS columns
            FROM pg_index i
            JOIN pg_class tc ON tc.oid = i.indrelid
            JOIN pg_namespace n ON n.oid = tc.relnamespace
            JOIN pg_class ic ON ic.oid = i.indexrelid
            JOIN pg_am am ON am.oid = ic.relam
            JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS k(attnum, ord) ON true
            LEFT JOIN pg_attribute a ON a.attrelid = tc.oid AND a.attnum = k.attnum
            WHERE n.nspname = $1
              AND tc.relname = $2
            GROUP BY ic.relname, i.indisunique, am.amname
            ORDER BY ic.relname
            "#,
        )
        .bind(&schema)
        .bind(&table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut indexes = Vec::new();
        for row in index_rows {
            let name: String = row.try_get(0).unwrap_or_default();
            let unique: bool = row.try_get(1).unwrap_or(false);
            let index_type: String = row.try_get(2).unwrap_or_default();
            let columns: Option<Vec<String>> = row.try_get(3).ok();
            indexes.push(IndexInfo {
                name,
                unique,
                index_type: if index_type.is_empty() {
                    None
                } else {
                    Some(index_type)
                },
                columns: columns.unwrap_or_default(),
            });
        }

        let fk_rows = sqlx::query(
            r#"
            SELECT
              con.conname AS constraint_name,
              a.attname AS column_name,
              fn.nspname AS referenced_schema,
              fc.relname AS referenced_table,
              fa.attname AS referenced_column,
              CASE con.confupdtype::text
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
                ELSE NULL
              END AS on_update,
              CASE con.confdeltype::text
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
                ELSE NULL
              END AS on_delete
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_class fc ON fc.oid = con.confrelid
            JOIN pg_namespace fn ON fn.oid = fc.relnamespace
            JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS ck(attnum, ord) ON true
            JOIN LATERAL unnest(con.confkey) WITH ORDINALITY AS fk(attnum, ord) ON fk.ord = ck.ord
            JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ck.attnum
            JOIN pg_attribute fa ON fa.attrelid = fc.oid AND fa.attnum = fk.attnum
            WHERE con.contype = 'f'
              AND n.nspname = $1
              AND c.relname = $2
            ORDER BY con.conname, ck.ord
            "#,
        )
        .bind(&schema)
        .bind(&table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut foreign_keys = Vec::new();
        for row in fk_rows {
            let referenced_schema: String = row.try_get(2).unwrap_or_default();
            foreign_keys.push(ForeignKeyInfo {
                name: row.try_get(0).unwrap_or_default(),
                column: row.try_get(1).unwrap_or_default(),
                referenced_schema: if referenced_schema.is_empty() {
                    None
                } else {
                    Some(referenced_schema)
                },
                referenced_table: row.try_get(3).unwrap_or_default(),
                referenced_column: row.try_get(4).unwrap_or_default(),
                on_update: row.try_get::<Option<String>, _>(5).unwrap_or(None),
                on_delete: row.try_get::<Option<String>, _>(6).unwrap_or(None),
            });
        }

        Ok(TableMetadata {
            columns,
            indexes,
            foreign_keys,
            clickhouse_extra: None,
            cassandra_extra: None,
            special_type_summaries: vec![],
        })
    }

    async fn load_pg_columns(
        &self,
        schema: &str,
        table: &str,
    ) -> Result<Vec<PgColumnInfo>, AppError> {
        let rows = sqlx::query(
            r#"
            SELECT
              a.attname AS column_name,
              format_type(a.atttypid, a.atttypmod) AS column_type,
              a.attnotnull AS not_null,
              pg_get_expr(ad.adbin, ad.adrelid) AS column_default,
              a.attidentity::text AS attidentity
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_attribute a ON a.attrelid = c.oid
            LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
            WHERE n.nspname = $1
              AND c.relname = $2
              AND a.attnum > 0
              AND NOT a.attisdropped
            ORDER BY a.attnum
            "#,
        )
        .bind(schema)
        .bind(table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut cols = Vec::new();
        for row in rows {
            let name = decode_postgres_text_cell(&row, 0)?;
            let data_type = decode_postgres_text_cell(&row, 1)?;
            let not_null: bool = row.try_get(2).unwrap_or(false);
            let default_value = decode_postgres_optional_text_cell(&row, 3)?;
            let identity: Option<String> = row
                .try_get::<Option<String>, _>(4)
                .unwrap_or(None)
                .and_then(|v| if v.is_empty() { None } else { Some(v) });

            cols.push(PgColumnInfo {
                name,
                data_type,
                is_nullable: !not_null,
                default_value,
                identity,
            });
        }
        Ok(cols)
    }

    async fn load_pg_constraints(
        &self,
        schema: &str,
        table: &str,
    ) -> Result<
        (
            Vec<PgKeyConstraint>,
            Vec<ForeignKeyInfo>,
            Vec<(String, String)>,
        ),
        AppError,
    > {
        let rows = sqlx::query(
            r#"
            SELECT
              con.conname,
              con.contype::text AS contype,
              array_agg(a.attname ORDER BY ord.ord) FILTER (WHERE a.attname IS NOT NULL) AS columns,
              pg_get_constraintdef(con.oid, true) AS condef,
              fn.nspname AS ref_schema,
              fc.relname AS ref_table,
              array_agg(fa.attname ORDER BY ford.ord) FILTER (WHERE fa.attname IS NOT NULL) AS ref_columns,
              CASE con.confupdtype::text
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
                ELSE NULL
              END AS on_update,
              CASE con.confdeltype::text
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
                ELSE NULL
              END AS on_delete
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            LEFT JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS ord(attnum, ord) ON true
            LEFT JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ord.attnum
            LEFT JOIN pg_class fc ON fc.oid = con.confrelid
            LEFT JOIN pg_namespace fn ON fn.oid = fc.relnamespace
            LEFT JOIN LATERAL unnest(con.confkey) WITH ORDINALITY AS ford(attnum, ord)
              ON con.contype = 'f' AND ford.ord = ord.ord
            LEFT JOIN pg_attribute fa ON fa.attrelid = fc.oid AND fa.attnum = ford.attnum
            WHERE n.nspname = $1
              AND c.relname = $2
              AND con.contype IN ('p', 'u', 'c', 'f')
            GROUP BY con.conname, con.contype, con.oid, fn.nspname, fc.relname,
                     con.confupdtype, con.confdeltype
            ORDER BY
              CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 WHEN 'f' THEN 3 END,
              con.conname
            "#,
        )
        .bind(schema)
        .bind(table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut key_constraints = Vec::new();
        let mut foreign_keys = Vec::new();
        let mut check_constraints = Vec::new();

        for row in rows {
            let conname: String = row.try_get(0).unwrap_or_default();
            let contype: String = row.try_get(1).unwrap_or_default();
            let columns: Option<Vec<String>> = row.try_get(2).ok();

            match contype.as_str() {
                "p" | "u" => {
                    let constraint_type = if contype == "p" {
                        "PRIMARY KEY".to_string()
                    } else {
                        "UNIQUE".to_string()
                    };
                    key_constraints.push(PgKeyConstraint {
                        name: conname,
                        constraint_type,
                        columns: columns.unwrap_or_default(),
                    });
                }
                "c" => {
                    let condef: String = row.try_get(3).unwrap_or_default();
                    if !condef.is_empty() {
                        check_constraints.push((conname, condef));
                    }
                }
                "f" => {
                    let col_list = columns.unwrap_or_default();
                    let col = col_list.first().cloned().unwrap_or_default();
                    let referenced_schema: Option<String> =
                        row.try_get::<Option<String>, _>(4).unwrap_or(None);
                    let referenced_table: String = row.try_get(5).unwrap_or_default();
                    let ref_columns: Option<Vec<String>> = row.try_get(6).ok();
                    let referenced_column = ref_columns
                        .and_then(|c| c.first().cloned())
                        .unwrap_or_default();
                    foreign_keys.push(ForeignKeyInfo {
                        name: conname,
                        column: col,
                        referenced_schema,
                        referenced_table,
                        referenced_column,
                        on_update: row.try_get::<Option<String>, _>(7).unwrap_or(None),
                        on_delete: row.try_get::<Option<String>, _>(8).unwrap_or(None),
                    });
                }
                _ => {}
            }
        }

        Ok((key_constraints, foreign_keys, check_constraints))
    }

    async fn load_pg_indexes(
        &self,
        schema: &str,
        table: &str,
    ) -> Result<Vec<PgIndexInfo>, AppError> {
        let rows = sqlx::query(
            r#"
            SELECT
              ic.relname AS index_name,
              i.indisunique AS is_unique,
              am.amname AS index_type,
              i.indkey,
              pg_get_indexdef(i.indexrelid) AS full_def,
              pg_get_expr(i.indpred, i.indrelid) AS condition
            FROM pg_index i
            JOIN pg_class tc ON tc.oid = i.indrelid
            JOIN pg_namespace tn ON tn.oid = tc.relnamespace
            JOIN pg_class ic ON ic.oid = i.indexrelid
            JOIN pg_am am ON am.oid = ic.relam
            WHERE tn.nspname = $1
              AND tc.relname = $2
              AND NOT i.indisprimary
              AND i.indisvalid
              AND NOT EXISTS (
                SELECT 1 FROM pg_constraint con
                WHERE con.conindid = i.indexrelid
              )
            ORDER BY ic.relname
            "#,
        )
        .bind(schema)
        .bind(table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut indexes = Vec::new();
        for row in rows {
            let name: String = row.try_get(0).unwrap_or_default();
            let unique: bool = row.try_get(1).unwrap_or(false);
            let index_type: String = row.try_get(2).unwrap_or_default();
            let indkey: Vec<i16> = row.try_get::<Vec<i16>, _>(3).unwrap_or_default();
            let full_def: String = row.try_get(4).unwrap_or_default();
            let condition: Option<String> = row.try_get::<Option<String>, _>(5).unwrap_or(None);

            let has_expression = indkey.iter().any(|&k| k == 0);

            let columns = if !has_expression {
                let mut cols = Vec::new();
                for &attnum in &indkey {
                    if attnum > 0 {
                        let col_rows = sqlx::query_scalar::<_, String>(
                            "SELECT attname FROM pg_attribute WHERE attrelid = \
                             (SELECT oid FROM pg_class WHERE relname = $1 \
                              AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = $2)) \
                             AND attnum = $3",
                        )
                        .bind(table)
                        .bind(schema)
                        .bind(attnum as i32)
                        .fetch_optional(&self.pool)
                        .await
                        .map_err(|e| query_error(e.to_string()))?;
                        if let Some(col) = col_rows {
                            cols.push(col);
                        }
                    }
                }
                cols
            } else {
                extract_pg_index_columns(&full_def).unwrap_or_default()
            };

            indexes.push(PgIndexInfo {
                name,
                unique,
                index_type,
                columns,
                condition,
                full_statement: full_def,
            });
        }
        Ok(indexes)
    }

    async fn load_pg_comments(
        &self,
        schema: &str,
        table: &str,
    ) -> Result<(Option<String>, HashMap<String, String>), AppError> {
        let table_comment: Option<String> = sqlx::query_scalar(
            r#"
            SELECT d.description
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_description d ON d.objoid = c.oid AND d.objsubid = 0
            WHERE n.nspname = $1 AND c.relname = $2
            "#,
        )
        .bind(schema)
        .bind(table)
        .fetch_optional(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?
        .flatten();

        let comment_rows = sqlx::query(
            r#"
            SELECT a.attname, d.description
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_attribute a ON a.attrelid = c.oid
            JOIN pg_description d ON d.objoid = c.oid AND d.objsubid = a.attnum
            WHERE n.nspname = $1
              AND c.relname = $2
              AND a.attnum > 0
              AND NOT a.attisdropped
            "#,
        )
        .bind(schema)
        .bind(table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut col_comments = HashMap::new();
        for row in comment_rows {
            let col_name: String = row.try_get(0).unwrap_or_default();
            let comment: String = row.try_get(1).unwrap_or_default();
            if !comment.is_empty() {
                col_comments.insert(col_name, comment);
            }
        }

        Ok((table_comment, col_comments))
    }

    pub async fn get_table_ddl(&self, schema: String, table: String) -> Result<String, AppError> {
        let columns = self.load_pg_columns(&schema, &table).await?;
        let (key_constraints, foreign_keys, check_constraints) =
            self.load_pg_constraints(&schema, &table).await?;
        let indexes = self.load_pg_indexes(&schema, &table).await?;
        let (table_comment, column_comments) = self.load_pg_comments(&schema, &table).await?;

        Ok(render_pg_create_table_ddl(
            &schema,
            &table,
            &columns,
            &key_constraints,
            &check_constraints,
            &foreign_keys,
            &indexes,
            table_comment.as_deref(),
            &column_comments,
        ))
    }

    pub async fn get_schema_overview(
        &self,
        schema: Option<String>,
    ) -> Result<SchemaOverview, AppError> {
        let rows = if let Some(s) = schema {
            sqlx::query(
                "SELECT table_schema, table_name, column_name, data_type \
             FROM information_schema.columns \
             WHERE table_schema = $1 \
             ORDER BY table_schema, table_name, ordinal_position",
            )
            .bind(s)
            .fetch_all(&self.pool)
            .await
        } else {
            sqlx::query(
                "SELECT table_schema, table_name, column_name, data_type \
             FROM information_schema.columns \
             WHERE table_schema NOT IN ('information_schema', 'pg_catalog') \
             ORDER BY table_schema, table_name, ordinal_position",
            )
            .fetch_all(&self.pool)
            .await
        };

        let rows = rows.map_err(|e| {
            tracing::error!(error = %e, "Postgres schema overview query failed");
            query_error("Failed to fetch schema overview")
        })?;

        let mut tables_map: std::collections::HashMap<(String, String), Vec<ColumnSchema>> =
            std::collections::HashMap::new();

        for row in rows {
            let schema_name = decode_postgres_text_cell(&row, 0)
                .map_err(|e| AppError::internal(format!("Postgres table_schema: {}", e)))?;
            let table_name = decode_postgres_text_cell(&row, 1)
                .map_err(|e| AppError::internal(format!("Postgres table_name: {}", e)))?;
            let col_name = decode_postgres_text_cell(&row, 2)
                .map_err(|e| AppError::internal(format!("Postgres column_name: {}", e)))?;
            let data_type = decode_postgres_text_cell(&row, 3)
                .map_err(|e| AppError::internal(format!("Postgres data_type: {}", e)))?;

            let key = (schema_name, table_name);
            tables_map.entry(key).or_default().push(ColumnSchema {
                name: col_name,
                r#type: data_type,
            });
        }

        let mut tables = Vec::new();
        for ((schema_name, table_name), columns) in tables_map {
            tables.push(TableSchema {
                schema: schema_name,
                name: table_name,
                columns,
            });
        }

        tables.sort_by(|a, b| a.schema.cmp(&b.schema).then(a.name.cmp(&b.name)));

        Ok(SchemaOverview { tables })
    }

    pub async fn load_high_precision_columns(
        &self,
        schema: &str,
        table: &str,
    ) -> Result<HashSet<String>, AppError> {
        let rows = sqlx::query(
            "SELECT column_name, data_type, udt_name \
            FROM information_schema.columns \
            WHERE table_schema = $1 AND table_name = $2",
        )
        .bind(schema)
        .bind(table)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(format!("Failed to load column types: {e}")))?;

        let mut cols = HashSet::new();
        for row in rows {
            let col_name = decode_postgres_text_cell(&row, 0)?;
            let data_type = decode_postgres_text_cell(&row, 1)?;
            let udt_name = decode_postgres_text_cell(&row, 2)?;
            if is_high_precision_pg_type(&data_type, &udt_name) {
                cols.insert(col_name);
            }
        }
        Ok(cols)
    }

    pub async fn list_routines(
        &self,
        schema: Option<String>,
    ) -> Result<Vec<RoutineInfo>, AppError> {
        let rows = if let Some(schema) = schema {
            sqlx::query(
                "SELECT n.nspname AS schema_name, \
                        p.proname AS routine_name, \
                        CASE WHEN p.prokind = 'p' THEN 'procedure' ELSE 'function' END AS routine_type \
                 FROM pg_proc p \
                 JOIN pg_namespace n ON n.oid = p.pronamespace \
                 WHERE n.nspname = $1 \
                   AND p.prokind IN ('f', 'p') \
                 ORDER BY routine_type, p.proname",
            )
            .bind(&schema)
            .fetch_all(&self.pool)
            .await
            .map_err(|e| query_error(e.to_string()))?
        } else {
            sqlx::query(
                "SELECT n.nspname AS schema_name, \
                        p.proname AS routine_name, \
                        CASE WHEN p.prokind = 'p' THEN 'procedure' ELSE 'function' END AS routine_type \
                 FROM pg_proc p \
                 JOIN pg_namespace n ON n.oid = p.pronamespace \
                 WHERE n.nspname NOT IN ('information_schema', 'pg_catalog', 'pg_toast') \
                   AND n.nspname NOT LIKE 'pg_toast%' \
                   AND p.prokind IN ('f', 'p') \
                 ORDER BY n.nspname, routine_type, p.proname",
            )
            .fetch_all(&self.pool)
            .await
            .map_err(|e| query_error(e.to_string()))?
        };

        let mut res = Vec::new();
        for row in rows {
            res.push(RoutineInfo {
                schema: decode_postgres_text_cell(&row, 0).unwrap_or_else(|_| "public".to_string()),
                name: decode_postgres_text_cell(&row, 1).unwrap_or_default(),
                r#type: decode_postgres_text_cell(&row, 2).unwrap_or_default(),
            });
        }
        Ok(res)
    }

    pub async fn get_routine_ddl(
        &self,
        schema: String,
        name: String,
        _routine_type: String,
    ) -> Result<String, AppError> {
        let row: (String,) = sqlx::query_as(
            "SELECT pg_get_functiondef(p.oid) \
             FROM pg_proc p \
             JOIN pg_namespace n ON n.oid = p.pronamespace \
             WHERE n.nspname = $1 AND p.proname = $2 \
             LIMIT 1",
        )
        .bind(&schema)
        .bind(&name)
        .fetch_one(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let ddl = row.0;
        if ddl.trim().is_empty() {
            return Err(AppError::not_found(format!(
                "Routine '{}.{}' does not exist or its definition is not visible",
                schema, name
            )));
        }
        Ok(ddl)
    }

    pub async fn list_sequences(
        &self,
        schema: Option<String>,
    ) -> Result<Vec<SequenceInfo>, AppError> {
        let target_schema = schema.unwrap_or_else(|| "public".to_string());

        let rows = sqlx::query(
            "SELECT schemaname, sequencename, data_type, start_value, increment_by \
             FROM pg_sequences \
             WHERE schemaname = $1 \
             ORDER BY sequencename",
        )
        .bind(&target_schema)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut res = Vec::new();
        for row in rows {
            res.push(SequenceInfo {
                schema: row.try_get::<String, _>(0).unwrap_or_default(),
                name: row.try_get::<String, _>(1).unwrap_or_default(),
                data_type: row.try_get::<String, _>(2).unwrap_or_default(),
                start_value: row.try_get::<Option<String>, _>(3).ok().flatten(),
                increment: row.try_get::<Option<String>, _>(4).ok().flatten(),
            });
        }
        Ok(res)
    }

    pub async fn list_types(&self, schema: Option<String>) -> Result<Vec<TypeInfo>, AppError> {
        let target_schema = schema.unwrap_or_else(|| "public".to_string());

        let rows = sqlx::query(
            "SELECT n.nspname, t.typname, \
                    CASE t.typtype \
                      WHEN 'e' THEN 'enum' \
                      WHEN 'c' THEN 'composite' \
                      WHEN 'r' THEN 'range' \
                      ELSE t.typtype \
                    END as category \
             FROM pg_type t \
             JOIN pg_namespace n ON t.typnamespace = n.oid \
             WHERE n.nspname = $1 \
               AND t.typtype IN ('e', 'c', 'r') \
               AND NOT EXISTS ( \
                 SELECT 1 FROM pg_class WHERE reltype = t.oid AND relkind != 'c' \
               ) \
             ORDER BY t.typname",
        )
        .bind(&target_schema)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut res = Vec::new();
        for row in rows {
            res.push(TypeInfo {
                schema: row.try_get::<String, _>(0).unwrap_or_default(),
                name: row.try_get::<String, _>(1).unwrap_or_default(),
                category: row.try_get::<String, _>(2).unwrap_or_default(),
            });
        }
        Ok(res)
    }

    pub async fn get_schema_foreign_keys(
        &self,
        _database: Option<&str>,
    ) -> Result<Vec<SchemaForeignKey>, AppError> {
        let rows = sqlx::query(
            r#"
            SELECT
              con.conname AS constraint_name,
              n.nspname AS source_schema,
              c.relname AS source_table,
              a.attname AS source_column,
              fn.nspname AS target_schema,
              fc.relname AS target_table,
              fa.attname AS target_column,
              CASE con.confupdtype::text
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
                ELSE NULL
              END AS on_update,
              CASE con.confdeltype::text
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
                ELSE NULL
              END AS on_delete
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_class fc ON fc.oid = con.confrelid
            JOIN pg_namespace fn ON fn.oid = fc.relnamespace
            JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS ck(attnum, ord) ON true
            JOIN LATERAL unnest(con.confkey) WITH ORDINALITY AS fk(attnum, ord) ON fk.ord = ck.ord
            JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ck.attnum
            JOIN pg_attribute fa ON fa.attrelid = fc.oid AND fa.attnum = fk.attnum
            WHERE con.contype = 'f'
            ORDER BY con.conname, ck.ord
            "#,
        )
        .fetch_all(&self.pool)
        .await
        .map_err(|e| query_error(e.to_string()))?;

        let mut foreign_keys = Vec::new();
        for row in rows {
            let source_schema: String = row.try_get(1).unwrap_or_default();
            let target_schema: String = row.try_get(4).unwrap_or_default();
            foreign_keys.push(SchemaForeignKey {
                name: row.try_get(0).unwrap_or_default(),
                source_schema: if source_schema.is_empty() {
                    None
                } else {
                    Some(source_schema)
                },
                source_table: row.try_get(2).unwrap_or_default(),
                source_column: row.try_get(3).unwrap_or_default(),
                target_schema: if target_schema.is_empty() {
                    None
                } else {
                    Some(target_schema)
                },
                target_table: row.try_get(5).unwrap_or_default(),
                target_column: row.try_get(6).unwrap_or_default(),
                on_update: row.try_get::<Option<String>, _>(7).unwrap_or(None),
                on_delete: row.try_get::<Option<String>, _>(8).unwrap_or(None),
            });
        }
        Ok(foreign_keys)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_high_precision_pg_type() {
        assert!(is_high_precision_pg_type("bigint", "int8"));
        assert!(is_high_precision_pg_type("numeric", "numeric"));
        assert!(is_high_precision_pg_type("money", "money"));
        assert!(!is_high_precision_pg_type("integer", "int4"));
        assert!(!is_high_precision_pg_type("text", "text"));
    }
}
